const HOME_PATH = process.env.PUBLIC_URL+'/'
const ME_PATH = HOME_PATH + 'Me'
const CAREER_PATH = HOME_PATH + 'Career'
const PROJECTS_PATH = HOME_PATH + 'Projects'
const CONTACTS_PATH = HOME_PATH + 'Contacts'


export {HOME_PATH, ME_PATH, CAREER_PATH, PROJECTS_PATH, CONTACTS_PATH}